### ISSUE TITLE
Implement option to confine the output to a subset of the current screen resolution 

### ISSUE THREAD

**Issue by scott092707** [emersion/wlr-randr#13]
I have a monitor (laptop screen) which has its bottom and right edge obscured by horizontal/vertical lines of varied garbage, which seems to oscillate/vibrate.

A typical tiled window is unreadable at the edges (the bottom damage is larger and (especially for a terminal) more difficult to ignore.)
Xrandr has an option --fb which sets the width and height, which in my case is enough to limit the output to the non-damaged
part of the screen in my Peppermint OS partition.
If the damage had been [also] in the left/top sections of the screen, i could have also used xrandr's --transform option's c/f sections to move  the rectangle down/right and out of range of that part of the screen's damage also.

"−−fb widthxheight
Reconfigures the screen to the specified size. All configured monitors must fit within this size. When this option is not provided, xrandr computes the smallest screen size that will hold the set of configured outputs; this option provides a way to override that behaviour."
For my use case, obviously I would not want this to apply to more than one output, as screen damage is limited to whatever screen is affected...

"−−transform a,b,c,d,e,f,g,h,i
Specifies a transformation matrix to apply on the output.
...
Typically, a and e corresponds to the scaling on the X and Y axes, **c and f corresponds to the translation on those axes**"

**Comment by emersion** [comment]
This isn't a feature widely supported by Wayland compositors, so not possible to support in wlr-randr.
