### ISSUE TITLE
No mouse on second monitor after rescaling

### ISSUE THREAD

**Issue by adigitoleo** [emersion/wlr-randr#14]
Hi, thanks for making this!

I wonder if someone can offer advice about using this tool to set up multiple monitors with different scaling, and still be able to move the mouse across both screens. Currently I do the following:

1. Start my compositor (dwl) which is configured to use normal (x1) scaling for all monitors by default.
2. Use an alias that calls this script with a predefined `--pos` argument to position the second screen (left/right)
3. Call this script again with the `--scale` argument to scale the second screen if necessary.

I often attach different screens because this is for a NUC box which I sometimes carry around. Everything is working fine except if I rescale the second screen, and then I can't move the mouse to it anymore. Is this a known issue? Are there any workarounds? Most of my workflow is keyboard driven, but occasionally the mouse is convenient (e.g. for web browsing).

Cheers

**Comment by emersion** [comment]
Please report this to your compositor. This doesn't seem like a wlr-randr bug. wlr-randr doesn't have control over the mouse.

Maybe it's because there's a gap in your output layout, so the mouse gets stuck at the edge of a screen.
