### ISSUE TITLE
wlr-randr fails to start with error message

### ISSUE THREAD

**Issue by strahlc** [emersion/wlr-randr#15]
After last update, my gnome has switched to wayland. Since `xrandr` doesn't work anymore, I tried to use `wlr-randr` instead, but `wlr-randr` fails to start with the following message "compositor doesn't support wlr-output-management-unstable-v1".

I'm not sure if this is a bug in `wlr-randr` or wayland?

**Comment by emersion** [comment]
GNOME doesn't support wlr-randr.

**Comment by strahlc** [comment]
I thought `wlr-randr` was an equivalent for `xrandr` when using wayland. I didn't realise that it only works under a certain desktop environment.
Which desktop environments does `wlr-randr` support? Do you know of any alternatives for gnome?

**Comment by emersion** [comment]
wlr-randr works in **wlr**oots based compositors. Maybe ask in a GNOME channel or forum how to do this in GNOME.
