### ISSUE TITLE
Consider tagging a release

### ISSUE THREAD

**Issue by ahesford** [emersion/wlr-randr#8]
I am interested in packaging wlr-randr for [Void Linux](https://voidlinux.org/), but it is against policy to admit non-release software into the repo. If you are comfortable with the status of wlr-randr, please consider tagging an official release.

**Comment by emersion** [comment]
Sure!

https://github.com/emersion/wlr-randr/releases/tag/v0.1.0

**Comment by ahesford** [comment]
Thanks for your fast action!
