### ISSUE TITLE
"error: XDG_RUNTIME_DIR not set in the environment."

### ISSUE THREAD

**Issue by poperigby** [emersion/wlr-randr#9]
I'm trying to get this to work on PostmarketOS with Phosh, but it keeps giving me this error:
```
error: XDG_RUNTIME_DIR not set in the environment.
failed to connect to display
```
I'm not really sure how to use wlr-randr, because I can't find any documentation.

**Comment by emersion** [comment]
You need to start wlr-randr from inside the compositor session, where `XDG_RUNTIME_DIR` and `WAYLAND_DISPLAY` are set.

**Comment by poperigby** [comment]
Sorry about that. I realized that right after but forgot to close the issue.
